http:
    daemon: true
workers:
    messenger_consume_async:
        cmd: ['symfony', 'console', 'messenger:consume', 'async']
        watch: ['config', 'src', 'templates', 'vendor']
    docker_compose_up:
        cmd: ['docker compose', 'up', '-d']
        watch: ['compose.yaml', 'compose.override.yaml']
