services:
  ###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "3306"
  ###< doctrine/doctrine-bundle ###

  redis:
    ports:
      - "6379"

  ###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
  ###< symfony/mailer ###

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "80"
    depends_on:
      - database
    environment:
      PMA_HOST: database
      PMA_USER: root

  phpredisadmin:
    image: erikdubbelboer/phpredisadmin
    ports:
      - "80"
    depends_on:
      - redis
    environment:
      REDIS_1_HOST: redis
      REDIS_1_NAME: Docker